services:
  keycloak:
    container_name: keycloak-NS
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - keycloak-network
    command:
      - "start-dev"

networks:
  keycloak-network:
    driver: bridge

